### ISSUE TITLE
swiftmac todos

### ISSUE THREAD

**Issue by tvraman** [robertmeta/swiftmac#28] opened 2024-04-14 02:38 UTC
1. Add function swiftmac-configure to mac-voices.el. 2. Update logic in voice-setup  by adding swiftmac to the if-mac test. 3. Move any/all swiftmac setup into swiftmac-configure.

**Comment by robertmeta** [comment] 2024-04-16 19:13
@parhamdoustdar This is the one I would love your help with, getting these three pieces in place.

**Comment by robertmeta** [comment] 2024-04-17 12:53
From other ticket, merged into this one (I think there is an official way to merge tickets but I didn't bother finding it). 


This is a large ticket to create a swiftmac-setup.el that would do stuff like

setup defcustoms for the settings swiftmac supports
use dynamic voice selection (need separate ticket for this)
add to key places in the code like the multi servers, example:
(push "swiftmac" tts-multi-engines)
make it use new features like tts_set_pitch_multiplier and if possible tts_set_voice instead of the embedded voice codes, in a perfect world, no more embeddings / codes
(maybe) allow different voices for like comments versus code, I think I would like this
(maybe) new features like rate change on numbers.

**Comment by bartbunting** [comment] 2024-04-23 00:25
If nobody else is working on this bit, I'm happy to have a crack. Although my elisp is not that great sure I can make something work and polish from there also happy to collaborate if somebody has a start already

**Comment by robertmeta** [comment] 2024-04-23 17:40
@bartbunting features are in now, [{voice ...}] and [[pitch ...]] both as codes, would love your help with this, as I am still chasing a rare bug in swiftmac and want to focus on sharpwin after that.  Sharpwin will follow whatever you create for swiftmac, just tweaked for windows voices and such.

**Comment by tvraman** [comment] 2024-04-23 17:56
I dont know if the mac server was remote-tts capable, but if possible,
it would be nice for swiftmac to enable the remote tts feature a la
linux; it would make the Mac a more attractive client for those wishing
to program in the cloud.

On Linux this is done via a small TCL wrapper (tcl because the main
server is TCL), that wrapper basically opens a tcp socket, dups that to
stdin/stdout and lets the main server to do the work as usual.

--

**Comment by robertmeta** [comment] 2024-04-23 18:47
So, the "swiftmac" version you saw was a find and replace that had broken 
things so it was rolled back.  I had turned "emacspeak" into "eswiftmacspeak"
among other mistakes and invalid replacements.  

Due to incompatibilities between mac and swiftmac, we will need our own prefix
and need to change some things like rate into a float, etc. 

> On Apr 23, 2024, at 14:44, bartbunting ***@***.***> wrote:
> 
> 
> So I am slightly confused. We have a swiftmac-voices.el
> All the variables and defuns inside that were using swiftmac as their prefix.
> The recent commit has changed them back to using Mac as a prefix.
> I'm happy to work with anything but just want to be clear on if that was intentional or not. And what the correct answer is.
> If we keep Mac as the prefix in someways it seems more logical although it will likely break anybody who is still having a working Max server. That's not me. But not sure if anyone else does.
> It would be good to get some clarity on this before I go and change things.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

--
Robert Melton
***@***.***

**Comment by bartbunting** [comment] 2024-04-23 18:49
Another question is at the moment we define Paul as whatever the system default voice is. In someways that's great because people get the same voice in emacspeak that they defined as their system default on the Mac. In other way, it's annoying because we don't actually know what voice they're using and people may get an inconsistent result. my thought would be to set it to Alex by default and let people change it. Should they wish to.
That way everyone starts from a common place. Especially if we end up using actual voice changes rather than parameters given Ltd in how many knobs we have to turn at the moment.

**Comment by robertmeta** [comment] 2024-04-23 18:52
I feel like Alex is the most popular, but I am not 100% certain it is 
installed by default on 14+.  I am fine making the change because even
if you send junk, it will work because it will fallback to the valid 
system default voice. 

So, I agree with making it Alex. 

> On Apr 23, 2024, at 14:50, bartbunting ***@***.***> wrote:
> 
> 
> Another question is at the moment we define Paul as whatever the system default voice is. In someways that's great because people get the same voice in emacspeak that they defined as their system default on the Mac. In other way, it's annoying because we don't actually know what voice they're using and people may get an inconsistent result. my thought would be to set it to Alex by default and let people change it. Should they wish to.
> That way everyone starts from a common place. Especially if we end up using actual voice changes rather than parameters given Ltd in how many knobs we have to turn at the moment.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

--
Robert Melton
***@***.***

**Comment by robertmeta** [comment] 2024-04-23 21:15
@tvramen

Yeah, I actually got the code to add a -p in a branch somewhere, just need 
to reintegrate it and maybe make a wrapper launcher that just passes the 
flag, because swiftmac directly listens the port rather than routes data 
to stdin. 

> On Apr 23, 2024, at 13:57, T. V. Raman ***@***.***> wrote:
> 
> 
> I dont know if the mac server was remote-tts capable, but if possible,
> it would be nice for swiftmac to enable the remote tts feature a la
> linux; it would make the Mac a more attractive client for those wishing
> to program in the cloud.
> 
> On Linux this is done via a small TCL wrapper (tcl because the main
> server is TCL), that wrapper basically opens a tcp socket, dups that to
> stdin/stdout and lets the main server to do the work as usual.
> 
> -- 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

--
Robert Melton
***@***.***

**Comment by bartbunting** [comment] 2024-04-24 03:58
I have it working as far as I can tell.
However we are somewhat stuck in the fact that there is no nice way at the moment to make ACS work as we don't have multiple dimensions to work with.  It would be great if we could artificially create some using some post processing of the sound or something.
Anyway there are two patches, one to swiftmac for swiftmac-voices.el and one to emacspeak for voice-setup.el

I include below some lisp code to setup some voices.  This is user specific and depends on the actual voices being installed on your system.
This needs significant tuning and was more of a test than anything.

; define some voices so we can test things are working
(swiftmac-define-voice voice-bolden "[{voice en_US:Fred}]  [[pitch 0.8]]")
(swiftmac-define-voice voice-animate "[{voice en-US:Kit}] [[pitch 1]]")
(swiftmac-define-voice voice-animate-extra "[{voice en-US:Kit}] [[pitch 1.5 ]]")
(swiftmac-define-voice voice-lighten "[{voice en-AU:Matilda}] [[pitch 1]]")
(swiftmac-define-voice voice-lighten-extra "[{voice en-AU:Matilda}] [[pitch 1.1]]")
(swiftmac-define-voice voice-smoothen "[{voice en-UK:Daniel}] [[pitch 1]]")
(swiftmac-define-voice voice-monotone "[{voice en-US:Eddy}] [[pitch 1]]")
(swiftmac-define-voice voice-monotone-extra "[{voice en-US:Eddy}] [[pitch 1.5]]")


Let me know if it works for you.

 
[emacspeak.patch](https://github.com/robertmeta/swiftmac/files/15087590/emacspeak.patch)
[swiftmac.patch](https://github.com/robertmeta/swiftmac/files/15087593/swiftmac.patch)

**Comment by robertmeta** [comment] 2024-04-24 04:06
Thanks, this is super exciting!  I will try in the morning.  

On more customizations, I have a pathway to it but it requires a heavy 
lift that I won't start on till next stable release of Emacspeak.  

The problem is that I am highly sensitive to latency, so post processing 
in my experimentation can never take more than 50ms and feel acceptable 
to me on a m1. Right now notifications server manages to just barely stay
in this window but it is more forgiving in terms of feeling the latency. 

That 50ms also has to dump the Speech Synthesizer output to pcm and then 
do any processing, there is no way on MacOS to hook directly from the 
speech synthesis to AudioKit.

Now, with some optimization and concurrently processing the stream as 
I write it I think 50ms is doable, but I don't think I can get it 
working in like next couple days.  So stable will ship with swiftmac 
2.x and effects will be a 3.x feature.

Thanks again Bart! 


> On Apr 23, 2024, at 23:58, bartbunting ***@***.***> wrote:
> 
> 
> I have it working as far as I can tell.
> However we are somewhat stuck in the fact that there is no nice way at the moment to make ACS work as we don't have multiple dimensions to work with. It would be great if we could artificially create some using some post processing of the sound or something.
> Anyway there are two patches, one to swiftmac for swiftmac-voices.el and one to emacspeak for voice-setup.el
> I include below some lisp code to setup some voices. This is user specific and depends on the actual voices being installed on your system.
> This needs significant tuning and was more of a test than anything.
> ; define some voices so we can test things are working
> (swiftmac-define-voice voice-bolden "[{voice en_US:Fred}] [[pitch 0.8]]")
> (swiftmac-define-voice voice-animate "[{voice en-US:Kit}] [[pitch 1]]")
> (swiftmac-define-voice voice-animate-extra "[{voice en-US:Kit}] [[pitch 1.5 ]]")
> (swiftmac-define-voice voice-lighten "[{voice en-AU:Matilda}] [[pitch 1]]")
> (swiftmac-define-voice voice-lighten-extra "[{voice en-AU:Matilda}] [[pitch 1.1]]")
> (swiftmac-define-voice voice-smoothen "[{voice en-UK:Daniel}] [[pitch 1]]")
> (swiftmac-define-voice voice-monotone "[{voice en-US:Eddy}] [[pitch 1]]")
> (swiftmac-define-voice voice-monotone-extra "[{voice en-US:Eddy}] [[pitch 1.5]]")
> Let me know if it works for you.
> emacspeak.patch
> swiftmac.patch
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

--
Robert Melton
***@***.***

**Comment by robertmeta** [comment] 2024-04-24 17:53
@bartbunting Where would I do those voice definitions?

**Comment by robertmeta** [comment] 2024-04-24 17:57
@bartbunting nevermind, got it all working, updating docs, actually think we got everything on the list here.  Simplifies setup.  Cool stuff for v2!

**Closed by robertmeta** 2024-04-24 17:57 UTC
Labels: elisp
